# run: conda env create --file environment.yml
name: rkbfr-jump
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.11.7
    - numpy=1.23.5
    - pandas=2.1.4
    - scipy=1.11.4
    - arviz=0.18.0
    - matplotlib=3.8.2
    - scikit-fda=0.9.1
    - scikit-learn=1.4.0
    - numba=0.58.1
    - pip
    - pip:
      - Eryn==1.1.7
